# default configuration
lsi: false
safe: true
source: https://github.com/EncisoAlva/EncisoAlva.github.io.git
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge


remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-dinky

title: [Julio C Enciso-Alva]
description: [Persoal webpage for professional purposes]
