# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
- .jekyll-cache

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 3. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: art/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DrWholio # jekyll-seo-tag > Owners twitter username
author: DrWholio # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Julio Cesar Enciso-Alva # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://www.linkedin.com/in/julio-enciso-alva/
    - https://github.com/EncisoAlva
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Dallas # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Art # Needed for Siteleaf
    output: true
    description: "Outreach hobby project" # The post list page content
    feature_text: 'Glissettes and Bezier Curves'
    feature_image: "https://github.com/EncisoAlva/EncisoAlva.github.io/blob/main/img/banner_tulip.jpg?raw=true"

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-US # Set the site language
title: "JC Enciso-Alva" # Site name or title, also used in jekyll-seo-tag
logo: "https://github.com/EncisoAlva/EncisoAlva.github.io/blob/main/img/pic2.jpg?raw=true" # Site logo, also used in jekyll-seo-tag
description: 'Personal website for academic purposes.' # Site description and default description, also used in jekyll-seo-tag
permalink: pretty
# url: "https://alembic.darn.es" # Site url, also used in jekyll-seo-tag
# baseurl: ""
repo: "https://github.com/EncisoAlva/EncisoAlva.github.io"
email: "juliocesar.encisoalva@mavs.uta.edu"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "EncisoAlva" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/RBL@16px.png'
  32: '/assets/logos/RBL@32px.png'
  96: '/assets/logos/RBL@96px.png'
  120: '/assets/logos/RBL@120px.png'
  144: '/assets/logos/RBL@144px.png'
  180: '/assets/logos/RBL@180px.png'
  512: '/assets/logos/RBL@512px.png'
  1024: '/assets/logos/RBL@1024px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
- title: About me
  url: /about/
- title: Art
  url: /art/
- title: Research
  url: /research/
- title: CV
  url: https://github.com/EncisoAlva/EncisoAlva.github.io/blob/main//files/EncisoAlva_CV.pdf?raw=true

navigation_footer:
- title: Template by David Darnes
  url: https://darn.es

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://x.com/DrWholio
  LinkedIn: https://www.linkedin.com/in/julio-enciso-alva/
  GitHub: https://github.com/EncisoAlva

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  LinkedIn: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
